### ISSUE TITLE
Resourceful - What, Why

### ISSUE THREAD

**Issue by 7ranceaddic7** [net-lisias-ksp/KSP-Recall#7]
Is this TS?
What is it?
Why is it there?

I ask because KSP_Recall does this ...

[LOG 14:35:15.411] [KSP_Recall] INFO: Removing Resourceful support for kerbalEVA () due this part is not supported..
[LOG 14:35:15.411] [KSP_Recall] INFO: Removing Resourceful support for kerbalEVAfemale () due this part is not supported..
[LOG 14:35:15.411] [KSP_Recall] INFO: Removing Resourceful support for kerbalEVAVintage () due this part is not supported..
[LOG 14:35:15.411] [KSP_Recall] INFO: Removing Resourceful support for kerbalEVAfemaleVintage () due this part is not supported..
[LOG 14:35:15.411] [KSP_Recall] INFO: Removing Resourceful support for kerbalEVAFuture () due this part is not supported..
[LOG 14:35:15.411] [KSP_Recall] INFO: Removing Resourceful support for kerbalEVAfemaleFuture () due this part is not supported..

But, kerbalEVA* still has this ...

		MODULE
		{
			name = Resourceful
			active = True
		}

What am I missing?

**Comment by Lisias** [comment]
Ouch... I completely forgot about this.

That is how things **used** to work: On Main Menu, and **BEFORE** the first savegame is loaded on that session, you could withdraw a Module from a part by removing its entry from the prefab's (i.e., removing the node from the GameDatabase).

However, this is not working anymore. I still haven't dug too much on this matter, but what I know for sure is that this stunt doesn't works anymore. I need to write a new way to withdraw programatically the module from the part.

In TweakScale I created a flag to deactivate the module before trying to remove it - so on KSP < 1.8 would still withdraw the module, and KSP >= would just have it deactivated (besides eating memory and CPU resources, as the module would be still be called on some events).

I will tackle down this problem on the WeekEnd in a way or another.

Keep in mind that KSP-Recall **is not needed** on anything but KSP 1.9 by now. If you run KSP 1.8 or earlier, or KSP 1.10, you **don't need it** and it's probably a better idea to get rid of it.

(at least, until I code something to fix a problem on some other KSP version, but until there...)

**Comment by 7ranceaddic7** [comment]
Oh, that's my bad.
Sorry, This was **1.9.1**


Not moving on to 1.10 for a while.
Have 1.8 as a backtest option.

**Comment by Lisias** [comment]
There was a problem on the deactivating code.

It was tackled down on https://github.com/net-lisias-ksp/KSP-Recall/commit/c8b1c40fb711a654680b35da4b4a71af3e8c7d1e

Additionally, the patching mechanism is smarter nowadays, detecting the need for the patch **before** patching, instead of patching everything and the Kitchen's sink and then removing when not needed. See https://github.com/net-lisias-ksp/KSP-Recall/commit/d1211fb05f72ec8ab91278774dd4cad7a6bb4305

**Comment by 7ranceaddic7** [comment]
BTW, you know these two (Resourceful, Driftless) show up in the PAW, right?

(Enable/Disable are essentially pointless in VAB/SPH, right?)

**Comment by Lisias** [comment]
Humm... nice catch.

The Resourceful trigger is useful on the VAB, because it also acts while editing crafts (it's what prevents symetrical parts to lose the properties of their parent).

But the Driftless is useless on Editor, it should appears only on Flight. :/

Well.... New release on the works.
